# Filter, Drop Nulls, Dedupe
1. Filter
For consistency, only compare cars certified by California standards. Filter both datasets using query to select only rows where cert_region is CA. Then, drop the cert_region columns, since it will no longer provide any useful information (we'll know every value is 'CA').

2. Drop Nulls
Drop any rows in both datasets that contain missing values.

3. Dedupe
Drop any duplicate rows in both datasets.

In [138]:
# load datasets
import pandas as pd
df_08 = pd.read_csv('all_alpha_08.csv')

df_18 = pd.read_csv('all_alpha_18.csv')

In [139]:
# view dimensions of dataset
df_08.shape

(2404, 18)

In [140]:
# view dimensions of dataset
df_18.shape

(1611, 18)

In [141]:
df_08.head()

,Model,Displ,Cyl,Trans,Drive,Fuel,Sales Area,Stnd,Underhood ID,Veh Class,Air Pollution Score,FE Calc Appr,City MPG,Hwy MPG,Cmb MPG,Unadj Cmb MPG,Greenhouse Gas Score,SmartWay
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXT03.7PKR,SUV,7,Drv,15,20,17,22.0527,4,no
1,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,FA,B5,8HNXT03.7PKR,SUV,6,Drv,15,20,17,22.0527,4,no
2,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXT02.3DKR,SUV,7,Drv,17,22,19,24.1745,5,no
3,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,FA,B5,8HNXT02.3DKR,SUV,6,Drv,17,22,19,24.1745,5,no
4,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXV03.5HKR,midsize car,7,Drv,16,24,19,24.5629,5,no

Drop extraneous columns
Drop features that aren't consistent (not present in both datasets) or aren't relevant to our aim.

Columns to Drop:
From 2008 dataset: 'Stnd', 'Underhood ID', 'FE Calc Appr', 'Unadj Cmb MPG'
From 2018 dataset: 'Stnd', 'Stnd Description', 'Underhood ID', 'Comb CO2'

In [142]:
df_08.drop(['Stnd', 'Underhood ID', 'FE Calc Appr', 'Unadj Cmb MPG'], axis=1, inplace=True)
df_18.drop(['Stnd', 'Stnd Description', 'Underhood ID', 'Comb CO2'], axis=1, inplace=True)

Rename Columns
Change the "Sales Area" column label in the 2008 dataset to "Cert Region" for consistency.

In [143]:
df_08.rename(columns = {'Sales Area':'Cert Region'}, inplace=True)

Rename all column labels to replace spaces with underscores and convert everything to lowercase.
Being consistent with lowercase and underscores makes things easier.

In [144]:
df_08.rename(columns = lambda x: x.strip().lower().replace(" ", "_"), inplace=True)
df_18.rename(columns = lambda x: x.strip().lower().replace(" ", "_"), inplace=True)

Confirm column labels for 2008 and 2018 datasets are identical

df_08.columns == df_18.columns(df_08.columns == df_18.columns).all()

Querying and Dropping
For consistency, only compare cars certified by 'California standards', filter both datasets using 'query()' 
to select only rows where cert_region is CA. Then, drop the cert_region columns, since it will no longer 
provide any useful information.

In [145]:
#Filter by Certification Region

df_08 = df_08.query('cert_region=="CA"')

In [146]:
#filter datasets for rows following California standards
df_08 = df_08.query('cert_region=="CA"')
df_18 = df_18.query('cert_region=="CA"')

In [147]:
# confirm only certification region is California
df_08['cert_region'].unique()

array(['CA'], dtype=object)

In [148]:
# confirm only certification region is California
df_18['cert_region'].unique()

array(['CA'], dtype=object)

In [149]:
# drop certification region columns form both datasets

df_08 = df_08.drop('cert_region', axis=1) 
df_18 = df_18.drop('cert_region', axis=1)

In [150]:
df_18.shape

(798, 13)

Drop Rows with Missing Values

In [151]:
# view missing value count for each feature in 2008
df_08.isnull().sum()

model                    0
displ                    0
cyl                     75
trans                   75
drive                   37
fuel                     0
veh_class                0
air_pollution_score      0
city_mpg                75
hwy_mpg                 75
cmb_mpg                 75
greenhouse_gas_score    75
smartway                 0
dtype: int64

In [152]:
# view missing value count for each feature in 2018
df_18.isnull().sum()

model                   0
displ                   1
cyl                     1
trans                   0
drive                   0
fuel                    0
veh_class               0
air_pollution_score     0
city_mpg                0
hwy_mpg                 0
cmb_mpg                 0
greenhouse_gas_score    0
smartway                0
dtype: int64

In [153]:
# drop rows with any null values in both datasets
df_08.dropna(axis=0, inplace=True)
df_18.dropna(axis=0, inplace=True)

In [154]:
# checks if any of columns in 2008 have null values - should print False
df_08.isnull().sum().any()

False

Dedupe Data

In [155]:
# print number of duplicates in 2008 and 2018 datasets
df_08.duplicated().sum()
df_18.duplicated().sum()

3

In [156]:
# drop duplicates in both datasets

df_08.drop_duplicates(inplace=True)
df_18.drop_duplicates(inplace=True)

In [157]:
# print number of duplicates again to confirm dedupe - should both be 0
df_08.duplicated().sum()
df_18.duplicated().sum()

0

In [158]:
# save progress for the next section
df_08.to_csv('data_08.csv', index=False)
df_18.to_csv('data_18.csv', index=False)

1)Fix 'cyl' datatype (it's categorical):
2008: extract int from str using 'regular expression', then convert to int.
2018: convert float to int...using 'astype(int)'.

In [159]:
df_08['cyl'].value_counts()
df_08['cyl'].str.extract('(\d+)').astype(int)
df_08['cyl'].value_counts()

df_18['cyl'] = df_18['cyl'].astype(int)

2)Fix 'air_pollution_score' datatype
2008: convert string to float.
2018: convert int to float.

df_08.air_pollution_score = df_08.air_pollution_score.astype(float)
............ERROR

In [160]:
df_08.iloc[582]

model                   MERCEDES-BENZ C300
displ                                    3
cyl                                (6 cyl)
trans                              Auto-L7
drive                                  2WD
fuel                           ethanol/gas
veh_class                        small car
air_pollution_score                    6/4
city_mpg                             13/18
hwy_mpg                              19/25
cmb_mpg                              15/21
greenhouse_gas_score                   7/6
smartway                                no
Name: 1550, dtype: object

In [161]:
hb_08 = df_08[df_08['fuel'].str.contains('/')]; hb_08

,model,displ,cyl,trans,drive,fuel,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
1550,MERCEDES-BENZ C300,3.0,(6 cyl),Auto-L7,2WD,ethanol/gas,small car,6/4,13/18,19/25,15/21,7/6,no

In [162]:
hb_18 = df_18[df_18['fuel'].str.contains('/')]; hb_18

,model,displ,cyl,trans,drive,fuel,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
108,BMW 330e,2.0,4,SemiAuto-8,2WD,Gasoline/Electricity,small car,3,28/66,34/78,30/71,10,Yes
160,BMW 530e,2.0,4,SemiAuto-8,2WD,Gasoline/Electricity,small car,7,27/70,31/75,29/72,10,Elite
162,BMW 530e,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,small car,7,27/66,31/68,28/67,10,Elite
188,BMW 740e,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,large car,3,25/62,29/68,27/64,9,Yes
382,CHEVROLET Impala,3.6,6,SemiAuto-6,2WD,Ethanol/Gas,large car,5,14/18,20/28,16/22,4,No
394,CHEVROLET Silverado 15,4.3,6,Auto-6,2WD,Ethanol/Gas,pickup,5,12/18,16/24,14/20,4,No
396,CHEVROLET Silverado 15,4.3,6,Auto-6,4WD,Ethanol/Gas,pickup,5,12/17,15/22,13/19,3,No
398,CHEVROLET Silverado 15,5.3,8,Auto-6,2WD,Ethanol/Gas,pickup,3,12/16,17/23,14/19,3,No
428,CHEVROLET Suburban 1500,5.3,8,Auto-6,2WD,Ethanol/Gas,standard SUV,3,12/16,17/23,14/19,3,No
432,CHEVROLET Suburban 1500,5.3,8,Auto-6,4WD,Ethanol/Gas,standard SUV,3,11/16,15/22,12/18,3,No
436,CHEVROLET Tahoe 1500,5.3,8,Auto-6,2WD,Ethanol/Gas,standard SUV,3,12/16,17/23,14/19,3,No
440,CHEVROLET Tahoe 1500,5.3,8,Auto-6,4WD,Ethanol/Gas,standard SUV,3,11/16,16/22,13/18,3,No
454,CHEVROLET Volt,1.5,4,CVT,2WD,Gasoline/Electricity,small car,3,43/113,42/99,42/106,10,Yes
456,CHEVROLET Volt,1.5,4,CVT,2WD,Gasoline/Electricity,small car,7,43/113,42/99,42/106,10,Elite
458,CHRYSLER 300,3.6,6,Auto-8,2WD,Ethanol/Gas,large car,3,14/19,22/30,17/23,5,No
462,CHRYSLER 300,3.6,6,Auto-8,4WD,Ethanol/Gas,large car,3,13/18,20/27,16/21,4,No
492,DODGE Charger,3.6,6,Auto-8,2WD,Ethanol/Gas,large car,3,14/19,22/30,17/23,5,No
496,DODGE Charger,3.6,6,Auto-8,4WD,Ethanol/Gas,large car,3,13/18,20/27,16/21,4,No
605,FORD Fusion Energi Plug-in Hybrid,2.0,4,CVT,2WD,Gasoline/Electricity,midsize car,7,43/102,41/91,42/97,10,Elite
659,GMC Sierra 15,4.3,6,Auto-6,2WD,Ethanol/Gas,pickup,5,12/18,16/24,14/20,4,No
661,GMC Sierra 15,4.3,6,Auto-6,4WD,Ethanol/Gas,pickup,5,12/17,15/22,13/19,3,No
663,GMC Sierra 15,5.3,8,Auto-6,2WD,Ethanol/Gas,pickup,3,12/16,17/23,14/19,3,No
697,GMC Yukon 1500,5.3,8,Auto-6,2WD,Ethanol/Gas,standard SUV,3,12/16,17/23,14/19,3,No
701,GMC Yukon 1500,5.3,8,Auto-6,4WD,Ethanol/Gas,standard SUV,3,11/16,16/22,13/18,3,No
709,GMC Yukon 1500 XL,5.3,8,Auto-6,2WD,Ethanol/Gas,standard SUV,3,12/16,17/23,14/19,3,No
715,GMC Yukon XL 1500,5.3,8,Auto-6,4WD,Ethanol/Gas,standard SUV,3,11/16,15/22,12/18,3,No
892,JEEP Cherokee,2.4,4,Auto-9,2WD,Ethanol/Gas,small SUV,3,15/21,22/30,18/25,5,No
896,JEEP Cherokee,2.4,4,Auto-9,4WD,Ethanol/Gas,small SUV,3,14/21,21/28,17/23,5,No
933,KARMA Revero,2.0,4,Auto-1,2WD,Gasoline/Electricity,small car,1,20/59,21/61,20/60,10,No
1162,MERCEDES-BENZ CLA250 4Matic,2.0,4,AutoMan-7,4WD,Ethanol/Gas,small car,5,17/24,24/32,20/27,6,No
1179,MERCEDES-BENZ GLA250 4Matic,2.0,4,AutoMan-7,4WD,Ethanol/Gas,small SUV,5,17/23,23/31,19/26,5,No
1192,MERCEDES-BENZ GLE350 4Matic,3.5,6,Auto-7,4WD,Ethanol/Gas,standard SUV,3,13/18,17/22,14/19,3,No
1256,MINI Cooper SE Countryman All4,1.5,3,SemiAuto-6,4WD,Gasoline/Electricity,midsize car,3,28/63,27/66,27/65,9,Yes
1507,TOYOTA Sequoia FFV,5.7,8,SemiAuto-6,4WD,Ethanol/Gas,standard SUV,5,9/13,13/17,10/14,1,No
1517,TOYOTA Tundra FFV,5.7,8,SemiAuto-6,4WD,Ethanol/Gas,pickup,5,9/13,12/17,10/15,2,No
1577,VOLVO S90,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,midsize car,7,26/70,33/72,29/71,10,Elite
1601,VOLVO XC 60,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,small SUV,7,26/60,28/58,26/59,10,Elite
1609,VOLVO XC 90,2.0,4,SemiAuto-8,4WD,Gasoline/Electricity,standard SUV,7,26/63,30/61,27/62,10,Elite

In [163]:
df1 = hb_08.copy()  # data on 'first' fuel type of each hybrid vehicle
df2 = hb_08.copy()  # data on 'second' fuel type of each hybrid vehicle

df3 = hb_18.copy()
df4 = hb_18.copy()

In [164]:
split_columns_08 = ['fuel', 'air_pollution_score', 'city_mpg', 'hwy_mpg', 'cmb_mpg', 'greenhouse_gas_score']

split_columns_18 = ['fuel', 'city_mpg', 'hwy_mpg', 'cmb_mpg'] 
# No need to split for air_pollution_score or greenhouse_gas_score here because these columns are already 'ints' in the 2018 dataset.

In [165]:
for c in split_columns_08:
    df1[c] = df1[c].apply(lambda x: x.split("/")[0])
    df2[c] = df2[c].apply(lambda x: x.split("/")[1])
new_rows = df1.append(df2); new_rows

for c in split_columns_18:
    df3[c] = df3[c].apply(lambda x: x.split('/')[0])
    df4[c] = df4[c].apply(lambda x: x.split('/')[1])
new_rows2 = df3.append(df4); new_rows2

,model,displ,cyl,trans,drive,fuel,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
108,BMW 330e,2.0,4,SemiAuto-8,2WD,Gasoline,small car,3,28,34,30,10,Yes
160,BMW 530e,2.0,4,SemiAuto-8,2WD,Gasoline,small car,7,27,31,29,10,Elite
162,BMW 530e,2.0,4,SemiAuto-8,4WD,Gasoline,small car,7,27,31,28,10,Elite
188,BMW 740e,2.0,4,SemiAuto-8,4WD,Gasoline,large car,3,25,29,27,9,Yes
382,CHEVROLET Impala,3.6,6,SemiAuto-6,2WD,Ethanol,large car,5,14,20,16,4,No
394,CHEVROLET Silverado 15,4.3,6,Auto-6,2WD,Ethanol,pickup,5,12,16,14,4,No
396,CHEVROLET Silverado 15,4.3,6,Auto-6,4WD,Ethanol,pickup,5,12,15,13,3,No
398,CHEVROLET Silverado 15,5.3,8,Auto-6,2WD,Ethanol,pickup,3,12,17,14,3,No
428,CHEVROLET Suburban 1500,5.3,8,Auto-6,2WD,Ethanol,standard SUV,3,12,17,14,3,No
432,CHEVROLET Suburban 1500,5.3,8,Auto-6,4WD,Ethanol,standard SUV,3,11,15,12,3,No
436,CHEVROLET Tahoe 1500,5.3,8,Auto-6,2WD,Ethanol,standard SUV,3,12,17,14,3,No
440,CHEVROLET Tahoe 1500,5.3,8,Auto-6,4WD,Ethanol,standard SUV,3,11,16,13,3,No
454,CHEVROLET Volt,1.5,4,CVT,2WD,Gasoline,small car,3,43,42,42,10,Yes
456,CHEVROLET Volt,1.5,4,CVT,2WD,Gasoline,small car,7,43,42,42,10,Elite
458,CHRYSLER 300,3.6,6,Auto-8,2WD,Ethanol,large car,3,14,22,17,5,No
462,CHRYSLER 300,3.6,6,Auto-8,4WD,Ethanol,large car,3,13,20,16,4,No
492,DODGE Charger,3.6,6,Auto-8,2WD,Ethanol,large car,3,14,22,17,5,No
496,DODGE Charger,3.6,6,Auto-8,4WD,Ethanol,large car,3,13,20,16,4,No
605,FORD Fusion Energi Plug-in Hybrid,2.0,4,CVT,2WD,Gasoline,midsize car,7,43,41,42,10,Elite
659,GMC Sierra 15,4.3,6,Auto-6,2WD,Ethanol,pickup,5,12,16,14,4,No
661,GMC Sierra 15,4.3,6,Auto-6,4WD,Ethanol,pickup,5,12,15,13,3,No
663,GMC Sierra 15,5.3,8,Auto-6,2WD,Ethanol,pickup,3,12,17,14,3,No
697,GMC Yukon 1500,5.3,8,Auto-6,2WD,Ethanol,standard SUV,3,12,17,14,3,No
701,GMC Yukon 1500,5.3,8,Auto-6,4WD,Ethanol,standard SUV,3,11,16,13,3,No
709,GMC Yukon 1500 XL,5.3,8,Auto-6,2WD,Ethanol,standard SUV,3,12,17,14,3,No
715,GMC Yukon XL 1500,5.3,8,Auto-6,4WD,Ethanol,standard SUV,3,11,15,12,3,No
892,JEEP Cherokee,2.4,4,Auto-9,2WD,Ethanol,small SUV,3,15,22,18,5,No
896,JEEP Cherokee,2.4,4,Auto-9,4WD,Ethanol,small SUV,3,14,21,17,5,No
933,KARMA Revero,2.0,4,Auto-1,2WD,Gasoline,small car,1,20,21,20,10,No
1162,MERCEDES-BENZ CLA250 4Matic,2.0,4,AutoMan-7,4WD,Ethanol,small car,5,17,24,20,6,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
428,CHEVROLET Suburban 1500,5.3,8,Auto-6,2WD,Gas,standard SUV,3,16,23,19,3,No
432,CHEVROLET Suburban 1500,5.3,8,Auto-6,4WD,Gas,standard SUV,3,16,22,18,3,No
436,CHEVROLET Tahoe 1500,5.3,8,Auto-6,2WD,Gas,standard SUV,3,16,23,19,3,No
440,CHEVROLET Tahoe 1500,5.3,8,Auto-6,4WD,Gas,standard SUV,3,16,22,18,3,No
454,CHEVROLET Volt,1.5,4,CVT,2WD,Electricity,small car,3,113,99,106,10,Yes
456,CHEVROLET Volt,1.5,4,CVT,2WD,Electricity,small car,7,113,99,106,10,Elite
458,CHRYSLER 300,3.6,6,Auto-8,2WD,Gas,large car,3,19,30,23,5,No
462,CHRYSLER 300,3.6,6,Auto-8,4WD,Gas,large car,3,18,27,21,4,No
492,DODGE Charger,3.6,6,Auto-8,2WD,Gas,large car,3,19,30,23,5,No
496,DODGE Charger,3.6,6,Auto-8,4WD,Gas,large car,3,18,27,21,4,No
605,FORD Fusion Energi Plug-in Hybrid,2.0,4,CVT,2WD,Electricity,midsize car,7,102,91,97,10,Elite
659,GMC Sierra 15,4.3,6,Auto-6,2WD,Gas,pickup,5,18,24,20,4,No
661,GMC Sierra 15,4.3,6,Auto-6,4WD,Gas,pickup,5,17,22,19,3,No
663,GMC Sierra 15,5.3,8,Auto-6,2WD,Gas,pickup,3,16,23,19,3,No
697,GMC Yukon 1500,5.3,8,Auto-6,2WD,Gas,standard SUV,3,16,23,19,3,No
701,GMC Yukon 1500,5.3,8,Auto-6,4WD,Gas,standard SUV,3,16,22,18,3,No
709,GMC Yukon 1500 XL,5.3,8,Auto-6,2WD,Gas,standard SUV,3,16,23,19,3,No
715,GMC Yukon XL 1500,5.3,8,Auto-6,4WD,Gas,standard SUV,3,16,22,18,3,No
892,JEEP Cherokee,2.4,4,Auto-9,2WD,Gas,small SUV,3,21,30,25,5,No
896,JEEP Cherokee,2.4,4,Auto-9,4WD,Gas,small SUV,3,21,28,23,5,No
933,KARMA Revero,2.0,4,Auto-1,2WD,Electricity,small car,1,59,61,60,10,No
1162,MERCEDES-BENZ CLA250 4Matic,2.0,4,AutoMan-7,4WD,Gas,small car,5,24,32,27,6,No
1179,MERCEDES-BENZ GLA250 4Matic,2.0,4,AutoMan-7,4WD,Gas,small SUV,5,23,31,26,5,No
1192,MERCEDES-BENZ GLE350 4Matic,3.5,6,Auto-7,4WD,Gas,standard SUV,3,18,22,19,3,No
1256,MINI Cooper SE Countryman All4,1.5,3,SemiAuto-6,4WD,Electricity,midsize car,3,63,66,65,9,Yes
1507,TOYOTA Sequoia FFV,5.7,8,SemiAuto-6,4WD,Gas,standard SUV,5,13,17,14,1,No
1517,TOYOTA Tundra FFV,5.7,8,SemiAuto-6,4WD,Gas,pickup,5,13,17,15,2,No
1577,VOLVO S90,2.0,4,SemiAuto-8,4WD,Electricity,midsize car,7,70,72,71,10,Elite
1601,VOLVO XC 60,2.0,4,SemiAuto-8,4WD,Electricity,small SUV,7,60,58,59,10,Elite
1609,VOLVO XC 90,2.0,4,SemiAuto-8,4WD,Electricity,standard SUV,7,63,61,62,10,Elite

In [166]:
df_08.drop(hb_08.index, inplace=True)
df_08 = df_08.append(new_rows, ignore_index=True)
df_08[df_08['fuel'].str.contains('/')]    #check '/' are gone...

Empty DataFrame
Columns: [model, displ, cyl, trans, drive, fuel, veh_class, air_pollution_score, city_mpg, hwy_mpg, cmb_mpg, greenhouse_gas_score, smartway]
Index: []

In [167]:
df_18.drop(hb_18.index, inplace=True)
df_18 = df_18.append(new_rows2, ignore_index=True)
df_18[df_18['fuel'].str.contains('/')]    #check '/' are gone...

Empty DataFrame
Columns: [model, displ, cyl, trans, drive, fuel, veh_class, air_pollution_score, city_mpg, hwy_mpg, cmb_mpg, greenhouse_gas_score, smartway]
Index: []

In [168]:
# convert string to float for 2008 air pollution column
df_08.air_pollution_score = df_08.air_pollution_score.astype(float)

# convert int to float for 2018 air pollution column
df_18.air_pollution_score = df_18.air_pollution_score.astype(float)

3)Fix city_mpg, hwy_mpg, cmb_mpg datatypes
2008 and 2018: convert string to float.

In [169]:
mpg_columns = ['city_mpg','hwy_mpg','cmb_mpg']
for c in mpg_columns:
    df_18[c] = df_18[c].astype(float)
    df_08[c] = df_08[c].astype(float)

4)Fix greenhouse_gas_score datatype
2008: convert from float to int.
df_08['greenhouse_gas_score'] = df_08['greenhouse_gas_score'].astype(int)

In [175]:
 df_08['greenhouse_gas_score'] = df_08['greenhouse_gas_score'].astype(int)

In [176]:
df_08.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 987 entries, 0 to 986
Data columns (total 13 columns):
model                   987 non-null object
displ                   987 non-null float64
cyl                     987 non-null object
trans                   987 non-null object
drive                   987 non-null object
fuel                    987 non-null object
veh_class               987 non-null object
air_pollution_score     987 non-null float64
city_mpg                987 non-null float64
hwy_mpg                 987 non-null float64
cmb_mpg                 987 non-null float64
greenhouse_gas_score    987 non-null int32
smartway                987 non-null object
dtypes: float64(5), int32(1), object(7)
memory usage: 69.4+ KB

In [177]:
df_18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 832 entries, 0 to 831
Data columns (total 13 columns):
model                   832 non-null object
displ                   832 non-null float64
cyl                     832 non-null int32
trans                   832 non-null object
drive                   832 non-null object
fuel                    832 non-null object
veh_class               832 non-null object
air_pollution_score     832 non-null float64
city_mpg                832 non-null float64
hwy_mpg                 832 non-null float64
cmb_mpg                 832 non-null float64
greenhouse_gas_score    832 non-null int64
smartway                832 non-null object
dtypes: float64(5), int32(1), int64(1), object(6)
memory usage: 61.8+ KB

In [178]:
#confirm using 'dtypes'
df_08.dtypes
df_18.dtypes
df_08.dtypes == df_18.dtypes

model                    True
displ                    True
cyl                     False
trans                    True
drive                    True
fuel                     True
veh_class                True
air_pollution_score      True
city_mpg                 True
hwy_mpg                  True
cmb_mpg                  True
greenhouse_gas_score    False
smartway                 True
dtype: bool